from django import forms


class UserForm(forms.Form):
    city = forms.ChoiceField(choices=(
        (0, 'Другой'),
        (1, 'Ужгород'),
        (2, 'Харьков'),
        (3, 'Одесса'),
        (4, 'Днепр'),
        (5, 'Киев'),
        (6, 'Львов'),
        (7, 'Винница'),
        (8, 'Николаев'),
        (9, 'Кропивницкий'),
        (10, 'Луцк'),
        (11, 'Черновцы'),
        (12, 'Ровно'),
        (13, 'Ивано-Франковск'),
        (14, 'Житомир'),
        (15, 'Кривой Рог'),
        (16, 'Хмельницкий'),
        (17, 'Херсон'),
        (18, 'Черкассы'),
        (19, 'Чернигов'),
        (20, 'Полтава'),
        (21, 'Запорожье'),
        (22, 'Сумы'),
        (23, 'Мариуполь'),
        (24, 'Тернополь'),
    ))
    position = forms.ChoiceField(choices=(
        (1, 'System Architect'),
        (2, 'Senior Software Engineer'),
        (3, 'Senior Software Engineer'),
        (4, 'Team/Technical Lead'),
        (5, 'HTML Coder'),
        (6, 'Support'),
        (7, 'Director of Engineering / Program Director'),
        (8, 'QA Tech Lead'),
        (9, 'DevOps'),
        (10, 'Product Manager'),
        (11, 'Software Engineer'),
        (12, 'Sales manager'),
        (13, 'Junior QA engineer'),
        (14, 'HR'),
        (15, 'Project manager'),
        (16, 'Senior Project manager / Program Manager'),
        (17, 'Junior Software Engineer'),
        (18, 'Marketing'),
        (19, 'Data Scientist'),
        (20, 'DBA'),
        (21, 'Product Owner'),
        (22, 'Designer'),
        (23, 'Data Engineer'),
        (24, 'QA Manager'),
        (25, 'Senior QA engineer'),
        (26, 'Customer Success'),
        (27, 'Business analyst'),
        (28, 'SysAdmin'),
        (29, 'Security Specialist'),
        (30, 'System Analyst'),
        (31, 'Research Engineer'),
        (32, 'Scrum Master'),
        (33, 'BI Engineer'),
        (34, 'ERP / CRM'),
        (35, 'Data Analyst'),
        (36, 'Technical writer'),
        (37, 'Copywriter'),
    ))
    exp = forms.FloatField()
    current_job_exp = forms.FloatField()
    age = forms.IntegerField()
    sex = forms.ChoiceField(choices=(
        (1, 'женский'),
        (2, 'мужской')
    ))
    university = forms.ChoiceField(choices=(
        (-1, 'Нет вуза'),
        (0, 'Другой вуз'),
        (1, 'КНУСА'),
        (2, 'ХНУРЭ'),
        (3, 'ОНАС'),
        (4, 'КНУ им. Шевченко'),
        (5, 'ЛНУ им. Франко'),
        (6, 'Львовская Политехника'),
        (7, 'НТУУ «КПИ»'),
        (8, 'ВНУ им. Даля'),
        (9, 'ХНУ им. Каразина'),
        (10, 'ДонНУ им. Васыля Стуса'),
        (11, 'ДонНТУ'),
        (11, 'ЗНТУ'),
        (13, 'ЧНУ им. Федьковича'),
        (14, 'ВНТУ'),
        (15, 'НТУ «ХПИ»'),
        (16, 'ЧГУ им. Петра Могилы'),
        (17, 'ОНУ им. Мечникова'),
        (18, 'КНЭУ'),
        (19, 'ОНПУ'),
        (20, 'КНУТД'),
        (21, 'ДНУ им. Гончара'),
        (22, 'ЖГТУ'),
        (23, 'ЧНТУ'),
        (24, 'ДНУЖТ'),
        (25, 'НУПТ'),
        (26, 'НГУ [Днепропетровск]'),
        (27, 'ХНУ [г. Хмельницкий]'),
        (28, 'ХАИ'),
        (29, 'ХНЭУ'),
        (30, 'ГУТ'),
        (31, 'УКУ'),
        (32, 'НаУКМА'),
        (33, 'НметАУ'),
        (34, 'СумГУ'),
        (35, 'НАУ'),
        (36, 'НУК')
    ))
    education = forms.ChoiceField(choices=(
        (1, 'Еще студент'),
        (2, 'Высшее'),
        (3, 'Два высших'),
        (4, 'Незаконченное высшее'),
        (5, 'Кандидат'),
        (6, 'Техникум / Колледж'),
        (7, 'Среднее')
    ))
    programing_language = forms.ChoiceField(choices=(
        (-1, 'Не использую'),
        (0, 'Другой'),
        (1, 'C#/.NET'),
        (2, 'Python'),
        (3, 'Kotlin'),
        (4, 'Java'),
        (5, 'PHP'),
        (6, 'JavaScript'),
        (7, 'TypeScript'),
        (8, 'Clojure'),
        (9, 'Objective-C'),
        (10, '1С'),
        (11, 'C'),
        (12, 'Golang'),
        (13, 'Swift'),
        (14, 'Scala'),
        (15, 'C++'),
        (16, 'Erlang'),
        (17, 'Elixir'),
        (18, 'Rust'),
        (19, 'SQL'),
        (20, 'Delphi'),
        (21, 'Dart'),
        (22, 'APL'),
        (23, 'ABAP'),
        (24, 'Haskell'),
        (25, 'Perl'),
        (26, 'Groovy'),
        (27, 'R'),
        (28, 'Assembler'),
        (29, 'Flex/Flash/AIR'),
        (30, 'Ruby/Rails')
    ))
    english_level = forms.ChoiceField(choices=(
        (1, 'элементарный'),
        (2, 'ниже среднего'),
        (3, 'средний'),
        (4, 'выше среднего'),
        (5, 'продвинутый')
    ))
    company_size = forms.ChoiceField(choices=(
        (1, 'до 10 человек'),
        (2, 'до 50 человек'),
        (3, 'до 200 человек'),
        (4, 'до 10000 человек'),
        (5, 'свыше 1000 человек'),
    ))
    company_type = forms.ChoiceField(choices=(
        (0, 'Другая'),
        (1, 'Продуктовая'),
        (2, 'Аутсорсинговая'),
        (3, 'Стартап'),
        (4, 'Аутстаффинговая'),
    ))

